PARENT_PATH := $(shell cd ..; pwd)
CURDIR_PATH := $(shell pwd)
.PHONY: clean

clean:
	@rm -rf $(PARENT_PATH)/*.pyc
	@rm -rf $(CURDIR_PATH)/__pycache__
	@rm -rf $(PARENT_PATH)/.cache
	@rm -rf $(PARENT_PATH)/.ropeproject
	@rm -rf $(CURDIR_PATH)/.cache
	@rm -rf $(CURDIR_PATH)/.ropeproject
